### PR TITLE
Merge collection team branch to dev branch

### PR DESCRIPTION
**Pull request by Ovijavi**
collection team branch has some updated code from carmen that needs to be included

### CODE REVIEW

**Review by Ovijavi — COMMENTED** [review]
merging the collection team branch with dev

**Comment by Ovijavi** [comment]
don't know why it says there are still conflicting files, I resolved the ones that showed up on visual studio

**Review by Ovijavi — COMMENTED** [review]
reviewed all changes

**Comment by Max-Edelson** [comment]
Maybe cancel the PR and reopen it and see if the conflicts still exist @Ovijavi.

**Pull request closed without merging**
